version: "3.9"

services:

  api:
    build: .
    container_name: saas_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: saas_worker
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A app.worker.celery_app.celery_app worker --loglevel=info --concurrency=4

  beat:
    build: .
    container_name: saas_beat
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - worker
    command: celery -A app.worker.celery_app.celery_app beat --loglevel=info

  flower:
    build: .
    container_name: saas_flower
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    command: celery -A app.worker.celery_app.celery_app flower --port=5555

  db:
    image: postgres:15
    container_name: saas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pratyushcr7
      POSTGRES_DB: saas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: saas_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: